# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIFontIconDemo_Pods_osx' do
  pod 'SwiftUIFontIcon', :path => '../'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUIFontIconDemo_Pods_osx

end
